language: php
sudo: false
php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4snapshot
  - nightly

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer update --no-interaction

stages:
  - test
  - 7.1 test with prefer-lowest
  - 7.2 test with prefer-lowest
  - 7.3 test with prefer-lowest
  - 7.4 test with prefer-lowest
  - check style
  - phpstan analysis

script:
  - composer test

jobs:
  fast_finish: true
  allow_failures:
    - php: nightly
  include:
    - stage: 7.1 test with prefer-lowest
      install:
        - travis_retry composer update --no-interaction --prefer-lowest
      php: 7.1
      script:
        - composer test
    - stage: 7.2 test with prefer-lowest
      install:
        - travis_retry composer update --no-interaction --prefer-lowest
      php: 7.2
      script:
        - composer test
    - stage: 7.3 test with prefer-lowest
      install:
        - travis_retry composer update --no-interaction --prefer-lowest
      php: 7.3
      script:
        - composer test
    - stage: 7.4 test with prefer-lowest
      install:
        - travis_retry composer update --no-interaction --prefer-lowest
      php: 7.4snapshot
      script:
        - composer test
    - stage: check style
      php: 7.3
      script:
        - composer check-style
    - stage: phpstan analysis
      php: 7.3
      script:
        - composer static-analysis
